"""Keep the maintained README inventory aligned with actual skill files."""

import argparse
from pathlib import Path


def inventory(root: Path) -> str:
    rows = ["## 项目文件构成", "",
            "<!-- Generated by scripts/check-project-inventory.py --write -->", "",
            "以下统计由当前文件生成。入口行数与参考文件数量不代表每次任务的实际上下文或 token 消耗。", "",
            "| Skill | 入口行数 | 配套 Markdown 文件数 |", "|---|---:|---:|"]
    skills = sorted(root.glob("plugins/*/skills/*/SKILL.md"))
    for skill in skills:
        references = [p for p in skill.parent.rglob("*.md")
                      if p.name not in {"SKILL.md", "README.md", "CHANGELOG.md"}
                      and "docs" not in p.relative_to(skill.parent).parts
                      and ".venv-tools" not in p.parts]
        rows.append(f"| {skill.parent.name} | {len(skill.read_text().splitlines())} | {len(references)} |")
    plugin_count = len({skill.parents[2] for skill in skills})
    testing_count = sum(skill.parents[2].name == "testing" for skill in skills)
    mcp_count = len(list(root.glob("plugins/testing/mcp-servers/*/pyproject.toml")))
    rows.extend(["", f"{plugin_count} 个插件共包含 {len(skills)} 个 Skills，测试插件包含 {testing_count} 个 Skills 和 {mcp_count} 个可选 MCP 服务。",
                 "模式需要的参考文件按需读取；模型耗时与 token 应以实际运行记录为准。", "", ""])
    return "\n".join(rows)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    path = root / "README.md"
    text = path.read_text()
    heading = "## 项目文件构成" if "## 项目文件构成" in text else "## Token 消耗分析"
    start, end = text.index(heading), text.index("## 快速开始")
    updated = text[:start] + inventory(root) + text[end:]
    if args.write:
        path.write_text(updated)
    elif updated != text:
        raise SystemExit("README inventory is stale; run scripts/check-project-inventory.py --write")
    else:
        print("Project inventory matches the current files.")


if __name__ == "__main__":
    main()
